odiseo_sylius_rbac_plugin:
    resource: "@OdiseoSyliusRbacPlugin/Resources/config/routing.yml"

odiseo_sylius_marketplace_plugin_admin:
    resource: "@OdiseoSyliusMarketplacePlugin/Resources/config/routing/admin.yaml"
    prefix: /admin

odiseo_sylius_marketplace_plugin_shop:
    resource: "@OdiseoSyliusMarketplacePlugin/Resources/config/routing/shop.yaml"
    prefix: /{_locale}/vendors
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

odiseo_sylius_marketplace_plugin_api:
    resource: "@OdiseoSyliusMarketplacePlugin/Resources/config/routing/api.yaml"
    prefix: /api
