# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Factory,Fixture,Migrations,Tests,Kernel.php}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    sylius.fixture.admin_user:
        class: App\Fixture\AdminUserFixture
        arguments:
            - '@sylius.manager.admin_user'
            - '@sylius.fixture.example_factory.admin_user'
        tags:
            - { name: sylius_fixtures.fixture }

    sylius.fixture.example_factory.admin_user:
        class: App\Factory\AdminUserExampleFactory
        arguments:
            - '@sylius.factory.admin_user'
            - '@sylius.repository.channel'
            - '%locale%'
            - '@file_locator'
            - '@sylius.image_uploader'
            - '@sylius.repository.channel'
            - '@sylius_plus.repository.role'

    app.sylius_rbac.access.checker.hardcoded_route_name_checker:
        class: App\Access\Checker\HardcodedRouteNameChecker
        decorates: odiseo_sylius_marketplace_plugin.sylius_rbac.access.checker.hardcoded_route_name_checker

    app.sylius_rbac.access.checker.administrator_access_checker:
        class: App\Access\Checker\AdministratorAccessChecker
        decorates: odiseo_sylius_marketplace_plugin.sylius_rbac.access.checker.administrator_access_checker
        arguments:
            - '@app.sylius_rbac.access.checker.administrator_access_checker.inner'
